// StackSizeAnalysis — conservative stack size estimation for spawned tasks.
//
// Walks all LLVM::LLVMFuncOp operations named __task_*_wrapper (generated by
// task.spawn lowering). For each, estimates the total stack usage by summing
// alloca sizes and transitively walking the call graph. If the estimate
// exceeds DEFAULT_STACK_LIMIT (1 MB), a warning is emitted. A "stack_size"
// integer attribute is attached to every analysed wrapper regardless.

#include "asc/Analysis/StackSizeAnalysis.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/BuiltinOps.h"

namespace asc {

//===----------------------------------------------------------------------===//
// Per-element size helper.
//===----------------------------------------------------------------------===//

static uint64_t getElementSize(mlir::Type elemType) {
  if (auto intTy = mlir::dyn_cast<mlir::IntegerType>(elemType))
    return (intTy.getWidth() + 7) / 8;
  if (mlir::isa<mlir::Float32Type>(elemType))
    return 4;
  if (mlir::isa<mlir::Float64Type>(elemType))
    return 8;
  if (mlir::isa<mlir::Float16Type>(elemType))
    return 2;
  if (auto arrTy = mlir::dyn_cast<mlir::LLVM::LLVMArrayType>(elemType))
    return arrTy.getNumElements() * getElementSize(arrTy.getElementType());
  if (mlir::isa<mlir::LLVM::LLVMStructType>(elemType))
    return 64; // conservative struct estimate
  if (mlir::isa<mlir::LLVM::LLVMPointerType>(elemType))
    return 8;
  return 8; // default pointer-size fallback
}

//===----------------------------------------------------------------------===//
// Stack estimation for func::FuncOp and LLVM::LLVMFuncOp.
//===----------------------------------------------------------------------===//

uint64_t StackSizeAnalysisPass::estimateStackUsage(mlir::func::FuncOp func) {
  uint64_t total = 0;
  func.walk([&](mlir::LLVM::AllocaOp alloca) {
    uint64_t elemSize = getElementSize(alloca.getElemType());

    // Check for array allocations (alloca T, count N).
    uint64_t count = 1;
    if (auto sizeOp = alloca.getArraySize().getDefiningOp()) {
      if (auto constOp = mlir::dyn_cast<mlir::LLVM::ConstantOp>(sizeOp)) {
        if (auto intAttr =
                mlir::dyn_cast<mlir::IntegerAttr>(constOp.getValue()))
          count = intAttr.getInt();
      }
    }
    total += elemSize * count;
  });
  return total;
}

uint64_t
StackSizeAnalysisPass::estimateStackUsageLLVM(mlir::LLVM::LLVMFuncOp func) {
  uint64_t total = 0;
  func.walk([&](mlir::LLVM::AllocaOp alloca) {
    uint64_t elemSize = getElementSize(alloca.getElemType());

    uint64_t count = 1;
    if (auto sizeOp = alloca.getArraySize().getDefiningOp()) {
      if (auto constOp = mlir::dyn_cast<mlir::LLVM::ConstantOp>(sizeOp)) {
        if (auto intAttr =
                mlir::dyn_cast<mlir::IntegerAttr>(constOp.getValue()))
          count = intAttr.getInt();
      }
    }
    total += elemSize * count;
  });
  return total;
}

//===----------------------------------------------------------------------===//
// Call-graph walking.
//===----------------------------------------------------------------------===//

uint64_t StackSizeAnalysisPass::walkCallGraph(
    mlir::func::FuncOp func, llvm::DenseSet<mlir::Operation *> &visited) {
  if (!visited.insert(func.getOperation()).second) {
    func->emitWarning("potential unbounded recursion detected in function '")
        << func.getName() << "' — stack size estimate may be inaccurate";
    return 0;
  }

  uint64_t local = estimateStackUsage(func);
  uint64_t maxCallee = 0;

  auto module = func->getParentOfType<mlir::ModuleOp>();

  func.walk([&](mlir::func::CallOp call) {
    if (auto calledFn =
            module.lookupSymbol<mlir::func::FuncOp>(call.getCallee())) {
      uint64_t calleeStack = walkCallGraph(calledFn, visited);
      maxCallee = std::max(maxCallee, calleeStack);
    }
  });

  visited.erase(func.getOperation());
  return local + maxCallee;
}

uint64_t StackSizeAnalysisPass::walkCallGraphLLVM(
    mlir::LLVM::LLVMFuncOp func,
    llvm::DenseSet<mlir::Operation *> &visited) {
  if (!visited.insert(func.getOperation()).second) {
    func->emitWarning("potential unbounded recursion detected in function '")
        << func.getName() << "' — stack size estimate may be inaccurate";
    return 0;
  }

  uint64_t local = estimateStackUsageLLVM(func);
  uint64_t maxCallee = 0;

  auto module = func->getParentOfType<mlir::ModuleOp>();

  // Task wrappers call func::FuncOp targets via func::CallOp.
  func.walk([&](mlir::func::CallOp call) {
    if (auto calledFn =
            module.lookupSymbol<mlir::func::FuncOp>(call.getCallee())) {
      uint64_t calleeStack = walkCallGraph(calledFn, visited);
      maxCallee = std::max(maxCallee, calleeStack);
    }
  });

  // Also check LLVM::CallOp for direct LLVM-level calls.
  func.walk([&](mlir::LLVM::CallOp call) {
    auto callee = call.getCallee();
    if (!callee)
      return;
    if (auto calledFn =
            module.lookupSymbol<mlir::LLVM::LLVMFuncOp>(*callee)) {
      uint64_t calleeStack = walkCallGraphLLVM(calledFn, visited);
      maxCallee = std::max(maxCallee, calleeStack);
    }
    // An LLVM::CallOp might also target a func::FuncOp.
    if (auto calledFn = module.lookupSymbol<mlir::func::FuncOp>(*callee)) {
      uint64_t calleeStack = walkCallGraph(calledFn, visited);
      maxCallee = std::max(maxCallee, calleeStack);
    }
  });

  visited.erase(func.getOperation());
  return local + maxCallee;
}

//===----------------------------------------------------------------------===//
// Main pass logic.
//===----------------------------------------------------------------------===//

void StackSizeAnalysisPass::runOnOperation() {
  auto module = getOperation();

  // Analyse task wrapper functions (generated by task.spawn lowering).
  // These are LLVM::LLVMFuncOp named __task_N_wrapper.
  module.walk([&](mlir::LLVM::LLVMFuncOp func) {
    if (!func.getName().starts_with("__task_"))
      return;

    llvm::DenseSet<mlir::Operation *> visited;
    uint64_t estimated = walkCallGraphLLVM(func, visited);

    if (estimated > DEFAULT_STACK_LIMIT) {
      func.emitWarning()
          << "spawned task estimated stack usage (" << estimated
          << " bytes) exceeds limit (" << DEFAULT_STACK_LIMIT << " bytes)";
    }

    // Attach stack_size attribute for potential runtime use / test inspection.
    func->setAttr("stack_size",
                  mlir::IntegerAttr::get(
                      mlir::IntegerType::get(func.getContext(), 64),
                      estimated));
  });
}

std::unique_ptr<mlir::Pass> createStackSizeAnalysisPass() {
  return std::make_unique<StackSizeAnalysisPass>();
}

} // namespace asc
